# examples:
# options mod1 option=val
# blacklist mod2

# NB: no sence in overlay-based filesystems try to change options her.
# Disable of modules via given file will work though, due to new feature of late removal.
